# Buyer Segmentation & Investment Profiling
## Data Loading and Data Preparation

In [1]:
import pandas as pd

## Step 1: Load the Datasets

In [2]:
clients = pd.read_excel("../Dataset/clients.xlsx")
properties = pd.read_excel("../Dataset/properties.xlsx")

## Step 2: Preview the Data

In [3]:
clients.head()

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,C0001,Individual,Kareem,Liu,1968-11-05 00:00:00,F,USA,California,Home,4,Yes,Website
1,C0002,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,C0003,Individual,Kale,Gay,1959-07-04 00:00:00,M,USA,California,Home,4,Yes,Agency
3,C0004,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,C0005,Company,Marleez,Co,2/28/1976,M,USA,California,Investment,5,No,Website

In [4]:
properties.head()

,listing_id,tower_number,transaction_date,unit_category,unit_number,floor_area_sqft,sale_price,listing_status,client_ref
0,1012,1,2024-01-01,Apartment,12,1160.36,"$300,385.62",Sold,C0027
1,1015,1,2024-01-01,Apartment,15,782.25,"$208,930.81",Sold,C0097
2,1021,1,2024-01-01,Apartment,21,756.21,"$218,585.92",Sold,C0113
3,1030,1,2024-01-01,Apartment,30,743.09,"$246,172.68",Sold,C0141
4,2016,2,2024-01-01,Apartment,16,701.66,"$212,265.67",Sold,C0146

## Step 3: Check Dataset Size

In [5]:
print("Clients Shape :", clients.shape)
print("Properties Shape :", properties.shape)

Clients Shape : (2000, 12)
Properties Shape : (10000, 9)

## Step 4: Check Data Types

In [6]:
clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   client_id            2000 non-null   object
 1   client_type          2000 non-null   object
 2   first_name           2000 non-null   object
 3   last_name            2000 non-null   object
 4   date_of_birth        2000 non-null   object
 5   gender               2000 non-null   object
 6   country              2000 non-null   object
 7   region               2000 non-null   object
 8   acquisition_purpose  2000 non-null   object
 9   satisfaction_score   2000 non-null   int64
 10  loan_applied         2000 non-null   object
 11  referral_channel     2000 non-null   object
dtypes: int64(1), object(11)
memory usage: 187.6+ KB

In [7]:
properties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   listing_id        10000 non-null  int64
 1   tower_number      10000 non-null  int64
 2   transaction_date  10000 non-null  datetime64[ns]
 3   unit_category     10000 non-null  object
 4   unit_number       10000 non-null  int64
 5   floor_area_sqft   10000 non-null  float64
 6   sale_price        10000 non-null  object
 7   listing_status    10000 non-null  object
 8   client_ref        7305 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 703.3+ KB

## Step 5: Check Missing Values

In [8]:
clients.isnull().sum()

client_id              0
client_type            0
first_name             0
last_name              0
date_of_birth          0
gender                 0
country                0
region                 0
acquisition_purpose    0
satisfaction_score     0
loan_applied           0
referral_channel       0
dtype: int64

In [9]:
properties.isnull().sum()

listing_id             0
tower_number           0
transaction_date       0
unit_category          0
unit_number            0
floor_area_sqft        0
sale_price             0
listing_status         0
client_ref          2695
dtype: int64

## Step 6: Check Duplicate Records

In [10]:
print("Client Duplicates :", clients.duplicated().sum())
print("Property Duplicates :", properties.duplicated().sum())

Client Duplicates : 0
Property Duplicates : 0

## Step 7: Merge the Datasets

In [12]:
merged = pd.merge(
    clients,
    properties,
    left_on="client_id",
    right_on="client_ref",
    how="inner"
)

## Step 8: Check the Merged Dataset

In [13]:
merged.head()

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,...,referral_channel,listing_id,tower_number,transaction_date,unit_category,unit_number,floor_area_sqft,sale_price,listing_status,client_ref
0,C0001,Individual,Kareem,Liu,1968-11-05 00:00:00,F,USA,California,Home,4,...,Website,90343,9,2024-01-10,Apartment,40,1090.32,"$351,419.29",Sold,C0001
1,C0001,Individual,Kareem,Liu,1968-11-05 00:00:00,F,USA,California,Home,4,...,Website,4051,4,2024-01-12,Apartment,51,1608.84,"$496,266.41",Sold,C0001
2,C0001,Individual,Kareem,Liu,1968-11-05 00:00:00,F,USA,California,Home,4,...,Website,150099,15,2025-01-05,Apartment,15,522.71,"$175,599.90",Sold,C0001
3,C0001,Individual,Kareem,Liu,1968-11-05 00:00:00,F,USA,California,Home,4,...,Website,30432,3,2025-01-12,Apartment,50,713.67,"$223,479.12",Sold,C0001
4,C0002,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,...,Website,150044,15,2024-01-01,Apartment,6,938.57,"$299,245.20",Sold,C0002

In [14]:
merged.shape

(7305, 21)

## Step 9: Convert Sale Price to Numeric

In [16]:
merged["sale_price"] = (
    merged["sale_price"]
        .astype(str)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
)

merged["sale_price"] = pd.to_numeric(
    merged["sale_price"],
    errors="coerce"
)

## Step 10: Verify Data Type

In [17]:
merged["sale_price"].dtype

dtype('float64')

In [18]:
merged["sale_price"].head()

0    351419.29
1    496266.41
2    175599.90
3    223479.12
4    299245.20
Name: sale_price, dtype: float64

## Step 11: Save the Cleaned Dataset

In [19]:
merged.to_excel("../Dataset/merged_data.xlsx", index=False)

## Data Loading Completed Successfully